export type ProductType = {
    id:number,
    attributes:{
        productName:string;
        slug:string;
        description:string;
        active:boolean;
        isFeatured:boolean;
        tipoProducto:string;
        tipoCabello:string;
        origin:string;
        price:number;
        marca:string;
        images:{
            data:{
                id:number,
                attributes:{
                    url:string
                }
            }[]
        };
        category:{
            data:{
                attributes:{
                    slug:string,
                    categoryName:string;
                };
            };
        };
    };
}